server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)，如果不设置，对于请求一些处理时间比较久的服务会报500超时
#ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  #ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  #ConnectTimeout: 5000

#上面的直接使用ribbon的超时设置因为feign也集成了ribbon所以会有依赖冲突，但不影响使用，下面采用
#feign中的超时设置，有同样的效果
feign:
  client:
    config:
      default:
        ConnectTimeOut: 5000
        ReadTimeOut: 5000

  #支持hystrix
  hystrix:
    enabled: true
